[package]
name = "ch32-hal"
version = "0.1.0"
edition = "2021"
authors = ["Andelf <andelf@gmail.com>"]
repository = "https://github.com/andelf/ch32-hal"
documentation = "https://docs.rs/ch32-hal"
homepage = "https://github.com/andelf/ch32-hal"
categories = []
description = ""
keywords = []
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
# ch32-metapac = { version = "0.0.4", features = ["memory-x", "rt"] }
ch32-metapac = { version = "0.0.4", features = [
    "memory-x",
    "rt",
], path = "../ch32-data/build/ch32-metapac" }

qingke = { version = "0.1.5", features = ["critical-section-impl"] }
qingke-rt = { version = "0.1.5", features = ["highcode"] }
#qingke-rt = { version = "0.1.5", path = "../qingke/qingke-rt", features = [
#    "highcode",
#] }
embedded-hal = { version = "1.0.0", package = "embedded-hal" }
critical-section = { version = "1.1.2" }
defmt = { version = "0.3.5", optional = true }
embassy-sync = { version = "0.5.0", optional = true }
embassy-futures = { version = "0.1.1", optional = true }
embassy-time-driver = { version = "0.1.0", features = [
    "tick-hz-1_000_000",
], optional = true }
embassy-time = { version = "0.3.0", features = [
    "tick-hz-1_000_000",
], optional = true }
nb = "1.1.0"
embedded-hal-nb = "1.0.0"

[build-dependencies]
ch32-metapac = { version = "0.0.4", default-features = false, features = [
    "metadata",
], path = "../ch32-data/build/ch32-metapac" }
proc-macro2 = "1.0.78"
quote = "1.0"

[features]
default = ["embassy"]
embassy = [
    "dep:embassy-sync",
    "dep:embassy-futures",
    "dep:embassy-time-driver",
    "dep:embassy-time",
]

ch32v203g6u6 = ["ch32-metapac/ch32v203g6u6"]
ch32v307vct6 = ["ch32-metapac/ch32v307vct6"]
ch32x033f8p6 = ["ch32-metapac/ch32x033f8p6"]
ch32x034f8p6 = ["ch32-metapac/ch32x034f8p6"]
ch32x034f8u6 = ["ch32-metapac/ch32x034f8u6"]
ch32x035c8t6 = ["ch32-metapac/ch32x035c8t6"]
ch32x035f7p6 = ["ch32-metapac/ch32x035f7p6"]
ch32x035f8u6 = ["ch32-metapac/ch32x035f8u6"]
ch32x035g8r6 = ["ch32-metapac/ch32x035g8r6"]
ch32x035g8u6 = ["ch32-metapac/ch32x035g8u6"]
ch32x035r8t6 = ["ch32-metapac/ch32x035r8t6"]
