[package]
name = "ch32v003-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
ch32-hal = { path = "../../", features = [
    "ch32v003f4u6",
    "defmt",
    "embassy",
], default-features = false }


# qingke-rt = { version = "0.1.5" }
qingke-rt = { version = "0.1.5", path = "../../../qingke/qingke-rt" }

# Not working for now
# defmt = "0.3"
# defmt-rtt = "0.4"

panic-halt = "0.2.0"

display-interface-spi = "0.5.0"
# mipidsi = "0.7.1"
# embedded-graphics = "0.8.1"
# embedded-hal-bus = "0.1.0"
qingke = { version = "0.1.7", path = "../../../qingke" }


[profile.release]
strip = false   # symbols are not flashed to the microcontroller, so don't strip them.
lto = true
opt-level = "z" # Optimize for size.
